In [70]:
import requests
from bs4 import BeautifulSoup
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2408]:
df = pd.read_csv("Companies_500.csv")
df

,Unnamed: 0,Title,Reviews,Ratings,Company Type,Salaries,Total Interviews,Total Jobs,Founded Year,Company Age,Websites
0,0,TCS,93.7k,3.7,IT Services & Consulting,8.9L,10.7k,177,1996.0,29.0,tcs.com
1,1,Accenture,59.3k,3.8,IT Services & Consulting,5.9L,8.4k,8.8k,1989.0,36.0,accenture.com
2,2,Wipro,55.1k,3.7,IT Services & Consulting,4.5L,5.8k,4.1k,1945.0,80.0,careers.wipro.com
3,3,Cognizant,52.4k,3.7,IT Services & Consulting,5.7L,5.7k,204,1994.0,31.0,cognizant.com
4,4,Capgemini,43.9k,3.7,IT Services & Consulting,4.4L,4.9k,2k,1967.0,58.0,capgemini.com
...,...,...,...,...,...,...,...,...,...,...,...
495,495,Infinite Computer Solutions,1.6k,3.4,IT Services & Consulting,12.7k,150,185,2001.0,24.0,infinite.com
496,496,Philips,1.6k,3.8,Consumer Electronics & Appliances,10.3k,160,119,1930.0,95.0,philips.com
497,497,Dr Lal PathLabs,1.6k,4.2,Healthcare,4.4k,130,58,1949.0,76.0,lalpathlabs.com
498,498,Honeywell Automation,1.6k,3.8,Industrial Automation,11.4k,104,1,1906.0,119.0,honeywell.com
499,499,Nuvoco Vistas,1.6k,4.1,Building Material,6.2k,99,20,2014.0,11.0,nuvoco.com

In [2409]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        500 non-null    int64
 1   Title             500 non-null    object
 2   Reviews           500 non-null    object
 3   Ratings           500 non-null    float64
 4   Company Type      478 non-null    object
 5   Salaries          500 non-null    object
 6   Total Interviews  500 non-null    object
 7   Total Jobs        500 non-null    object
 8   Founded Year      485 non-null    float64
 9   Company Age       485 non-null    float64
 10  Websites          500 non-null    object
dtypes: float64(3), int64(1), object(7)
memory usage: 43.1+ KB

In [2411]:
df.drop(["Unnamed: 0"],axis=1,inplace=True)
df

,Title,Reviews,Ratings,Company Type,Salaries,Total Interviews,Total Jobs,Founded Year,Company Age,Websites
0,TCS,93.7k,3.7,IT Services & Consulting,8.9L,10.7k,177,1996.0,29.0,tcs.com
1,Accenture,59.3k,3.8,IT Services & Consulting,5.9L,8.4k,8.8k,1989.0,36.0,accenture.com
2,Wipro,55.1k,3.7,IT Services & Consulting,4.5L,5.8k,4.1k,1945.0,80.0,careers.wipro.com
3,Cognizant,52.4k,3.7,IT Services & Consulting,5.7L,5.7k,204,1994.0,31.0,cognizant.com
4,Capgemini,43.9k,3.7,IT Services & Consulting,4.4L,4.9k,2k,1967.0,58.0,capgemini.com
...,...,...,...,...,...,...,...,...,...,...
495,Infinite Computer Solutions,1.6k,3.4,IT Services & Consulting,12.7k,150,185,2001.0,24.0,infinite.com
496,Philips,1.6k,3.8,Consumer Electronics & Appliances,10.3k,160,119,1930.0,95.0,philips.com
497,Dr Lal PathLabs,1.6k,4.2,Healthcare,4.4k,130,58,1949.0,76.0,lalpathlabs.com
498,Honeywell Automation,1.6k,3.8,Industrial Automation,11.4k,104,1,1906.0,119.0,honeywell.com
499,Nuvoco Vistas,1.6k,4.1,Building Material,6.2k,99,20,2014.0,11.0,nuvoco.com

In [2412]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             500 non-null    object
 1   Reviews           500 non-null    object
 2   Ratings           500 non-null    float64
 3   Company Type      478 non-null    object
 4   Salaries          500 non-null    object
 5   Total Interviews  500 non-null    object
 6   Total Jobs        500 non-null    object
 7   Founded Year      485 non-null    float64
 8   Company Age       485 non-null    float64
 9   Websites          500 non-null    object
dtypes: float64(3), object(7)
memory usage: 39.2+ KB

In [2413]:
df['Reviews'].unique()

array(['93.7k', '59.3k', '55.1k', '52.4k', '43.9k', '41.3k', '41.1k',
       '39.5k', '37.8k', '36.6k', '33k', '31k', '27.4k', '26.5k', '26.2k',
       '24.3k', '23.4k', '23.2k', '21.9k', '21.1k', '19.4k', '18.5k',
       '17.7k', '16.7k', '16.3k', '15.8k', '14.2k', '12.5k', '12.3k',
       '12k', '11.5k', '11.1k', '11.3k', '10.8k', '10.4k', '10.2k',
       '10.1k', '9.8k', '9.6k', '9.5k', '9.1k', '8.7k', '8.1k', '7.9k',
       '7.7k', '7.5k', '7.4k', '7.3k', '7.1k', '7k', '6.7k', '6.5k',
       '6.4k', '6.3k', '6.2k', '6.1k', '6k', '5.8k', '5.7k', '5.6k',
       '5.5k', '5.4k', '5.3k', '5.2k', '5.1k', '5k', '4.9k', '4.8k',
       '4.7k', '4.6k', '4.5k', '4.4k', '4.3k', '4.2k', '4.1k', '4k',
       '3.9k', '3.8k', '3.7k', '3.6k', '3.5k', '3.4k', '3.3k', '3.2k',
       '3.1k', '3k', '2.9k', '2.8k', '2.7k', '2.6k', '2.5k', '2.4k',
       '2.3k', '2.2k', '2.1k', '2k', '1.4k', '1.9k', '1.8k', '1.7k',
       '1.6k'], dtype=object)

In [2414]:
df['Total Interviews'].unique()

array(['10.7k', '8.4k', '5.8k', '5.7k', '4.9k', '2.3k', '7.7k', '2.5k',
       '4k', '3.9k', '3.2k', '1.8k', '1.7k', '1.5k', '5.1k', '2k', '675',
       '1.6k', '2.4k', '3k', '841', '2.9k', '1.1k', '1.3k', '2.1k', '567',
       '892', '1k', '544', '641', '1.4k', '1.2k', '683', '808', '974',
       '700', '543', '635', '486', '820', '571', '452', '490', '765',
       '882', '663', '433', '611', '607', '559', '651', '356', '419',
       '760', '499', '524', '247', '411', '321', '590', '778', '404',
       '762', '484', '398', '255', '357', '727', '771', '327', '445',
       '612', '414', '812', '494', '464', '320', '242', '319', '461',
       '871', '156', '262', '457', '271', '542', '338', '460', '344',
       '376', '548', '597', '545', '658', '434', '275', '309', '413',
       '501', '200', '600', '366', '250', '289', '369', '299', '348',
       '575', '349', '159', '335', '303', '168', '116', '157', '354',
       '384', '474', '444', '241', '770', '218', '615', '520', '336',
       '281', '633', '246', '235', '204', '286', '393', '416', '211',
       '189', '213', '268', '341', '272', '221', '277', '372', '160',
       '92', '219', '351', '259', '216', '215', '162', '238', '207',
       '261', '210', '317', '155', '182', '229', '627', '190', '239',
       '225', '172', '141', '368', '183', '325', '173', '209', '245',
       '208', '153', '166', '212', '180', '187', '86', '178', '80', '236',
       '88', '132', '265', '151', '125', '233', '142', '163', '176',
       '226', '292', '314', '56', '140', '267', '222', '243', '199',
       '169', '84', '196', '144', '138', '145', '203', '285', '186',
       '198', '256', '131', '137', '390', '115', '98', '257', '279',
       '148', '105', '312', '149', '126', '269', '313', '134', '240',
       '89', '152', '164', '112', '104', '184', '82', '139', '90', '307',
       '128', '228', '167', '103', '79', '73', '136', '133', '370', '143',
       '220', '202', '111', '197', '264', '123', '124', '165', '72',
       '328', '179', '298', '69', '67', '334', '95', '227', '121', '194',
       '108', '114', '122', '76', '158', '201', '113', '396', '75', '97',
       '106', '93', '129', '185', '377', '74', '96', '118', '91', '110',
       '192', '342', '119', '101', '565', '64', '564', '253', '54', '859',
       '553', '70', '99', '14', '175', '117', '146', '71', '66', '135',
       '60', '297', '150', '130'], dtype=object)

In [2418]:
df['Salaries'].unique()

array(['8.9L', '5.9L', '4.5L', '5.7L', '4.4L', '1.4L', '4.8L', '1.5L',
       '3.4L', '2.7L', '2.1L', '91.5k', '1.2L', '99.5k', '1.3L', '62.2k',
       '22.8k', '66.9k', '2L', '1.8L', '50k', '69.6k', '1.9L', '82.5k',
       '68.6k', '58.6k', '53.2k', '46.7k', '63.3k', '41.1k', '26.2k',
       '49.1k', '49.2k', '44.9k', '74.7k', '67.1k', '37.3k', '27.4k',
       '93.3k', '31.1k', '27k', '69k', '23.4k', '42.4k', '23.7k', '32.3k',
       '30.5k', '23k', '29k', '25.3k', '22.6k', '26.3k', '30.8k', '13.7k',
       '42.2k', '40.4k', '24.5k', '8.4k', '24.4k', '21.4k', '51.1k',
       '33k', '73.6k', '19.5k', '14.8k', '40.5k', '22.4k', '48.3k',
       '18.7k', '18.9k', '12.2k', '27.2k', '21.9k', '22.7k', '54.2k',
       '38k', '48.7k', '18.3k', '12.4k', '14.2k', '20.3k', '57.3k',
       '9.4k', '14.5k', '16.7k', '29.1k', '17k', '23.3k', '16k', '21.6k',
       '38.8k', '53.1k', '42k', '19k', '37.5k', '30.9k', '21.5k', '14.9k',
       '39.8k', '22.5k', '43.4k', '11.4k', '36.2k', '15.9k', '18.1k',
       '18.8k', '17.6k', '26.4k', '36.5k', '36.8k', '11.2k', '14.7k',
       '29.8k', '13.3k', '10.6k', '10.4k', '8.3k', '28.8k', '32k',
       '28.2k', '21k', '15.2k', '27.9k', '12.3k', '38.7k', '12.6k',
       '35.7k', '20.1k', '17.3k', '11k', '13.4k', '13.8k', '27.7k',
       '9.5k', '10.8k', '9k', '12k', '12.9k', '10.9k', '15.3k', '20k',
       '34.3k', '13.6k', '31.9k', '10.7k', '16.2k', '28.3k', '23.1k',
       '10.5k', '11.6k', '12.8k', '10k', '15.1k', '13.1k', '25k', '15.4k',
       '11.1k', '10.1k', '25.5k', '9.7k', '1.7k', '6.8k', '7.8k', '9.3k',
       '28.7k', '12.1k', '17.5k', '50', '7.9k', '16.3k', '26.1k', '27.5k',
       '7.6k', '6.3k', '8.9k', '11.5k', '5.1k', '7.3k', '23.6k', '8.5k',
       '9.1k', '19.6k', '8.7k', '17.1k', '13k', '9.6k', '20.5k', '7.7k',
       '8.6k', '18k', '8.1k', '7.1k', '20.7k', '6.6k', '5.4k', '16.6k',
       '3.2k', '18.4k', '5.6k', '9.2k', '4.6k', '6.4k', '6.5k', '3k',
       '8.2k', '4.2k', '10.2k', '8k', '4.9k', '5.3k', '3.9k', '4.7k',
       '11.8k', '16.8k', '7.4k', '7.5k', '13.9k', '5.9k', '9.9k', '7k',
       '4.3k', '6k', '5.8k', '5.5k', '11.7k', '2.6k', '5.7k', '3.5k',
       '5.2k', '13.5k', '6.9k', '17.7k', '6.7k', '4.4k', '1.3k', '15.5k',
       '6.2k', '4.8k', '15.6k', '788', '15.7k', '3.6k', '7.2k', '10.3k',
       '1.4k', '12.7k'], dtype=object)

In [2421]:
df['Total Jobs'].unique()

array(['177', '8.8k', '4.1k', '204', '2k', '529', '2.4k', '22', '227',
       '712', '461', '380', '137', '202', '2.2k', '116', '216', '119',
       '1k', '414', '152', '127', '61', '28', '--', '24', '182', '111',
       '14', '74', '2.9k', '113', '2.1k', '44', '203', '73', '54', '21',
       '135', '355', '159', '2', '348', '58', '468', '29', '71', '779',
       '90', '6', '197', '20', '154', '79', '87', '37', '18', '83', '194',
       '17', '411', '817', '102', '45', '91', '106', '169', '26', '1.1k',
       '1.2k', '249', '4', '210', '1', '27', '50', '23', '145', '53',
       '170', '146', '333', '525', '323', '673', '168', '16', '36', '112',
       '110', '200', '25', '39', '59', '70', '231', '47', '51', '100',
       '178', '49', '338', '7', '209', '46', '275', '55', '11', '5',
       '432', '30', '3', '13', '64', '85', '63', '9', '913', '89', '198',
       '19', '172', '12', '86', '141', '192', '239', '84', '8', '33',
       '162', '69', '144', '206', '57', '266', '40', '179', '138', '244',
       '727', '77', '313', '103', '48', '326', '115', '32', '31', '104',
       '319', '251', '68', '15', '65', '296', '242', '284', '107', '41',
       '147', '76', '42', '82', '35', '75', '99', '10', '160', '34', '78',
       '95', '98', '457', '133', '56', '66', '131', '108', '248', '329',
       '120', '148', '130', '271', '439', '38', '516', '163', '128',
       '281', '301', '287', '469', '253', '185'], dtype=object)

In [2510]:
df["Company Type"].unique()

array(['IT Services & Consulting', 'Banking', 'BPO', 'Internet',
       'Telecom', 'Retail', 'NBFC', 'Engineering & Construction',
       'Management Consulting', 'Oil & Gas', 'EdTech', 'Automobile',
       'Financial Services', 'Insurance', 'Unknown', 'FinTech',
       'Iron & Steel', 'Chemicals', 'Building Material',
       'Consumer Electronics & Appliances', 'Analytics & KPO', 'Pharma',
       'Logistics', 'FMCG', 'Software Product', 'Defence & Aerospace',
       'Real Estate', 'Industrial Automation', 'Healthcare',
       'Clinical Research', 'Auto Components', 'Fashion & Textile',
       'Beverage', 'Recruitment', 'Hospitality', 'Accounting & Auditing',
       'Electrical Equipment', 'Industrial Machinery',
       'Education & Training', 'Media & Entertainment',
       'Facility Management Services', 'Metals & Mining',
       'Electronics Manufacturing', 'Non-Profit', 'Agro Chemicals',
       'Aviation', 'Food Processing', 'Power', 'Hardware & Networking',
       'Law Enforcement & Security', 'Biotechnology', 'Railways', 'Other',
       'Jewellery', 'Packaging'], dtype=object)

In [2422]:
df.columns

Index(['Title', 'Reviews', 'Ratings', 'Company Type', 'Salaries',
       'Total Interviews', 'Total Jobs', 'Founded Year', 'Company Age',
       'Websites'],
      dtype='object')

In [2424]:
# def dtypeint(df):
#     l = ['Reviews'] #'Salaries', 'Total Interviews', 'Total Jobs', 'Founded Year', 'Company Age']
#     for i in l:
#         #for j in df[i]:
#             #if 'k' in j:
#         df[i] = df[i].replace('k','',regex = True)
#         df[i] = pd.to_numeric(df[i])
#         df[i] = df[i]*1000
#         df[i] = df[i].astype('int')

#     l2 = ['Salaries','Total Interviews','Total Jobs']
#     n=0
#     for i in l2:
#         while n<500:
#             if 'k' in df[i].iloc[n]:
#                 df[i].iloc[n] = df[i].iloc[n].replace('k','')
#             if 'L' in df[i].iloc[n]:
#                 df[i].iloc[n] = df[i].iloc[n].replace('L','')
#             n += 1
                
                
            
            #df[i] = df[i].replace('L','',regex = True)
            #df[i] = df[i].replace('k','',regex = True)
            #df[i] = df[i].replace('--',np.nan)
            #df[i] = pd.to_numeric(df[i])
        






        
                #df[i] = pd.to_numeric(df[i])
                #df[i] = df[i]*1000
        #if 'L' in df[i]:
        #    df[i] = df[i].replace("L","")
        #    df[i] = df[i].astype('int')
        #    df[i] = df[i]*100000
        #df[i] = df[i].astype('int')

In [2425]:
df['Total Jobs'] = df['Total Jobs'].replace('--',np.nan)

In [2428]:
def dtypeint(df):
    l = ['Reviews']                                         #'Salaries', 'Total Interviews', 'Total Jobs', 'Founded Year', 'Company Age']
    for i in l:
        #for j in df[i]:
            #if 'k' in j:
        df[i] = df[i].replace('k','',regex = True)
        df[i] = pd.to_numeric(df[i])
        df[i] = df[i]*1000
        df[i] = df[i].astype('int')

def sal(j):
    if 'k' in j:
        return float(j.replace('k',''))*1000
    elif 'L' in j:
        return float(j.replace('L',''))*100000
    else:
        return float(j)
    
def interv(j):
    if 'k' in j:
        return float(j.replace('k',''))*1000
    elif 'L' in j:
        return float(j.replace('L',''))*100000
    else:
        return float(j)

In [2429]:
df

,Title,Reviews,Ratings,Company Type,Salaries,Total Interviews,Total Jobs,Founded Year,Company Age,Websites
0,TCS,93.7k,3.7,IT Services & Consulting,8.9L,10.7k,177,1996.0,29.0,tcs.com
1,Accenture,59.3k,3.8,IT Services & Consulting,5.9L,8.4k,8.8k,1989.0,36.0,accenture.com
2,Wipro,55.1k,3.7,IT Services & Consulting,4.5L,5.8k,4.1k,1945.0,80.0,careers.wipro.com
3,Cognizant,52.4k,3.7,IT Services & Consulting,5.7L,5.7k,204,1994.0,31.0,cognizant.com
4,Capgemini,43.9k,3.7,IT Services & Consulting,4.4L,4.9k,2k,1967.0,58.0,capgemini.com
...,...,...,...,...,...,...,...,...,...,...
495,Infinite Computer Solutions,1.6k,3.4,IT Services & Consulting,12.7k,150,185,2001.0,24.0,infinite.com
496,Philips,1.6k,3.8,Consumer Electronics & Appliances,10.3k,160,119,1930.0,95.0,philips.com
497,Dr Lal PathLabs,1.6k,4.2,Healthcare,4.4k,130,58,1949.0,76.0,lalpathlabs.com
498,Honeywell Automation,1.6k,3.8,Industrial Automation,11.4k,104,1,1906.0,119.0,honeywell.com
499,Nuvoco Vistas,1.6k,4.1,Building Material,6.2k,99,20,2014.0,11.0,nuvoco.com

In [2432]:
df["Total Jobs"]

0       177
1      8.8k
2      4.1k
3       204
4        2k
       ...
495     185
496     119
497      58
498       1
499      20
Name: Total Jobs, Length: 500, dtype: object

In [2434]:
def jobs(j):
    if j == np.nan:
        return j
    elif 'k' in str(j):
        a = float(j.replace('k',''))*1000
        return a
    else:
        return float(j)

In [2436]:
df["Total Jobs"] = df["Total Jobs"].apply(jobs)

In [2439]:
#df['Total Jobs'].apply(jobs)

In [2442]:
# def jobs(df):
#     df[i] = df[i].replace('k','',regex= True)
#     df[i] = pd.to_numeric(df[i])
#     df[i].fillna(df[i].median(),inplace = True)

In [2443]:
#jobs(df)

In [2446]:
df['Total Jobs']

0       177.0
1      8800.0
2      4100.0
3       204.0
4      2000.0
        ...
495     185.0
496     119.0
497      58.0
498       1.0
499      20.0
Name: Total Jobs, Length: 500, dtype: float64

In [2447]:
# df['Total Jobs'] = df['Total Jobs'].replace('--',np.nan)

In [2450]:
# df['Total Jobs'] = pd.to_numeric(df['Total Jobs'])
# df['Total Jobs'] = df['Total Jobs'].apply(jobs)
# df['Total Jobs'].fillna(df['Total Jobs'].median(),inplace = True)

In [2451]:
dtypeint(df)
df['Salaries'] = df['Salaries'].apply(sal)
df['Total Interviews'] = df['Total Interviews'].apply(interv)
#df['Total Jobs'] = df['Total Jobs'].apply(jobs)

In [2454]:
df.columns

Index(['Title', 'Reviews', 'Ratings', 'Company Type', 'Salaries',
       'Total Interviews', 'Total Jobs', 'Founded Year', 'Company Age',
       'Websites'],
      dtype='object')

In [2456]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             500 non-null    object
 1   Reviews           500 non-null    int32
 2   Ratings           500 non-null    float64
 3   Company Type      478 non-null    object
 4   Salaries          500 non-null    float64
 5   Total Interviews  500 non-null    float64
 6   Total Jobs        442 non-null    float64
 7   Founded Year      485 non-null    float64
 8   Company Age       485 non-null    float64
 9   Websites          500 non-null    object
dtypes: float64(6), int32(1), object(3)
memory usage: 37.2+ KB

In [2459]:
def descrete(df):
    l1 = ['Founded Year']
    for i in l1:
        df[i].fillna(value='Not Available',inplace=True)

In [2461]:
descrete(df)

C:\Users\rake0\AppData\Local\Temp\ipykernel_24140\292508839.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(value='Not Available',inplace=True)
C:\Users\rake0\AppData\Local\Temp\ipykernel_24140\292508839.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Not Available' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df[i].fillna(value='Not Available',inplace=True)

In [2462]:
df[['Founded Year','Company Age']].isna().sum()

Founded Year     0
Company Age     15
dtype: int64

In [2465]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             500 non-null    object
 1   Reviews           500 non-null    int32
 2   Ratings           500 non-null    float64
 3   Company Type      478 non-null    object
 4   Salaries          500 non-null    float64
 5   Total Interviews  500 non-null    float64
 6   Total Jobs        442 non-null    float64
 7   Founded Year      500 non-null    object
 8   Company Age       485 non-null    float64
 9   Websites          500 non-null    object
dtypes: float64(5), int32(1), object(4)
memory usage: 37.2+ KB

In [2467]:
df[df['Total Jobs'].isna()]

,Title,Reviews,Ratings,Company Type,Salaries,Total Interviews,Total Jobs,Founded Year,Company Age,Websites
25,BYJU'S,16300,3.1,EdTech,58600.0,2100.0,NaN,2011.0,14.0,byjus.com
47,Tata Steel,7700,4.1,Iron & Steel,30500.0,882.0,NaN,1907.0,118.0,tatasteel.com
72,L&T Construction,6200,4.0,Engineering & Construction,18700.0,771.0,NaN,1944.0,81.0,lntecc.com
86,Indian Army,5400,4.7,Defence & Aerospace,9400.0,156.0,NaN,1895.0,130.0,indianarmy.nic.in
103,Standard Chartered,4800,3.7,Banking,39800.0,275.0,NaN,1853.0,172.0,sc.com
116,Citicorp,4600,3.7,Financial Services,44900.0,575.0,NaN,1997.0,28.0,citigroup.com
117,Hero MotoCorp,4500,4.1,Automobile,14900.0,349.0,NaN,1984.0,41.0,heromotocorp.com
139,State Bank of India,4000,3.8,Banking,11000.0,246.0,NaN,1806.0,219.0,sbi.co.in
161,Reliance Communications,3500,4.0,Telecom,10700.0,92.0,NaN,2002.0,23.0,rcom.co.in
164,Team Lease,3500,3.9,Recruitment,15300.0,213.0,NaN,2016.0,9.0,teamleasegroup.com
176,HDFC Ergo General Insurance,3300,3.9,Insurance,11600.0,155.0,NaN,2002.0,23.0,hdfcergo.com
200,Bharat Electronics,3100,4.2,Electronics Manufacturing,12000.0,212.0,NaN,1954.0,71.0,bel-india.in
204,Reliance Projects & Property Management Services,3100,4.0,IT Services & Consulting,6800.0,178.0,NaN,Not Available,NaN,ril.com
205,Indian Oil Corporation,3100,4.4,Oil & Gas,7800.0,211.0,NaN,1959.0,66.0,iocl.com
206,Future Group,3000,4.2,Retail,9300.0,80.0,NaN,2013.0,12.0,futuregroup.in
213,Marpu Foundation,3000,4.8,Non-Profit,50.0,88.0,NaN,2016.0,9.0,marpu.orgPrimary IndustryNon-ProfitOther Indus...
214,Reliance Digital,3000,4.1,Retail,7900.0,132.0,NaN,2007.0,18.0,reliancedigital.in
216,Ford Motor,3000,4.3,Automobile,14500.0,151.0,NaN,1903.0,122.0,corporate.ford.com
223,UBS,2900,3.9,Financial Services,29100.0,341.0,NaN,1998.0,27.0,ubs.com
226,Vishal Mega Mart,2900,3.7,Retail,6300.0,163.0,NaN,2008.0,17.0,vishalmegamart.com
229,JK Cement,2900,4.1,Building Material,8900.0,275.0,NaN,1975.0,50.0,jkcement.com
230,Honda Motorcycle & Scooter,2900,4.1,Automobile,10900.0,157.0,NaN,2001.0,24.0,honda2wheelersindia.com
233,Indian Air Force,2800,4.5,Defence & Aerospace,5100.0,56.0,NaN,1932.0,93.0,indianairforce.nic.in
244,NatWest Group,2800,4.0,Banking,19600.0,209.0,NaN,Not Available,NaN,natwestgroup.com
249,Whitehat jr,2700,3.4,EdTech,9500.0,262.0,NaN,2018.0,7.0,whitehatjr.com
250,UnitedHealth,2700,4.0,Healthcare,17100.0,84.0,NaN,1977.0,48.0,unitedhealthgroup.com
264,Amazon Transportation Services,2600,4.2,NaN,7600.0,229.0,NaN,2012.0,13.0,amazon.in
276,Barclays,2600,3.8,Banking,25500.0,279.0,NaN,1690.0,335.0,home.barclays
279,I Process Services,2500,3.9,NaN,5400.0,105.0,NaN,2005.0,20.0,iprocess.inPrimary Industry--Other IndustriesS...
293,Statestreet HCL Services,2300,3.3,BPO,15900.0,211.0,NaN,2012.0,13.0,statestreet.comPrimary IndustryBPOOther Indust...
299,IDFC FIRST Bharat,2300,4.4,Financial Services,4600.0,112.0,NaN,2016.0,9.0,idfcbharat.com
307,Shree Cement,2300,3.8,Building Material,9300.0,164.0,NaN,1979.0,46.0,shreecement.com
308,Domino's Pizza,2300,3.9,NaN,4200.0,90.0,NaN,1960.0,65.0,dominos.com
314,KPMG Global Services,2300,3.5,Management Consulting,20100.0,228.0,NaN,Not Available,NaN,kpmg.com
329,Patanjali Ayurved,2200,3.9,FMCG,6300.0,112.0,NaN,2006.0,19.0,patanjaliayurved.net
331,Blinkit,2200,3.7,Internet,9500.0,199.0,NaN,2013.0,12.0,blinkit.com
342,Taj Hotels Resorts and Palaces,2100,4.2,NaN,4700.0,123.0,NaN,1903.0,122.0,tajhotels.com
343,Sonalika Tractors,2100,3.7,Automobile,8500.0,133.0,NaN,1969.0,56.0,sonalika.com
355,Simplex Infrastructures,2000,3.3,Engineering & Construction,5600.0,69.0,NaN,1924.0,101.0,simplexinfra.com
361,Cholamandalam MS General Insurance,2000,3.8,Insurance,5800.0,95.0,NaN,2001.0,24.0,cholainsurance.com
376,JCB,2000,3.9,NaN,9000.0,138.0,NaN,1945.0,80.0,jcb.com
377,State Street Syntel,1900,3.7,Financial Services,8700.0,76.0,NaN,2004.0,21.0,syntelinc.com
383,Nokia Networks,1900,4.2,Hardware & Networking,11700.0,113.0,NaN,Not Available,NaN,nokia.com
388,Adani Power,2000,3.9,Power,8200.0,235.0,NaN,2006.0,19.0,adanipower.com
394,Indian Railways,1900,4.1,Railways,3500.0,89.0,NaN,1853.0,172.0,indianrailways.gov.in
397,Ola Electric Mobility,1900,3.3,Automobile,7700.0,235.0,NaN,2017.0,8.0,olaelectric.com
399,BHEL,1900,4.1,Electrical Equipment,5200.0,116.0,NaN,1964.0,61.0,bhel.com
416,Renault-Nissan,1800,4.1,NaN,7600.0,110.0,NaN,2007.0,18.0,alliancernm.com
423,Ambuja Cements,1800,3.9,Building Material,6000.0,113.0,NaN,1992.0,33.0,rmsi.com
428,Reliance Trends,1800,4.2,Retail,4400.0,106.0,NaN,2006.0,19.0,reliancetrends.com
440,Microsoft Corporation,1800,4.0,Software Product,22800.0,564.0,NaN,1975.0,50.0,microsoft.com
445,Delphi TVS,1700,3.9,Auto Components,5500.0,88.0,NaN,1989.0,36.0,delphitvs.com
448,Future Retail,1700,4.3,Retail,5200.0,54.0,NaN,1987.0,38.0,futureretail.co.in
450,Bharat Petroleum,1700,4.1,Oil & Gas,6600.0,152.0,NaN,1952.0,73.0,bharatpetroleum.com
455,ITC Hotels,1700,4.1,NaN,5400.0,86.0,NaN,1975.0,50.0,itchotels.in
471,Gabriel India,1600,4.2,Auto Components,5600.0,101.0,NaN,1961.0,64.0,anandgroupindia.com
477,IDBI Bank,1600,3.5,Banking,5700.0,71.0,NaN,1964.0,61.0,idbi.com
494,Hindustan Aeronautics,1600,4.3,Defence & Aerospace,4200.0,74.0,NaN,1940.0,85.0,hal-india.co.in

In [2470]:
df['Total Jobs'].fillna(value=0,inplace=True)
df['Company Age'].fillna(value=0,inplace=True)

C:\Users\rake0\AppData\Local\Temp\ipykernel_24140\4274336270.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Total Jobs'].fillna(value=0,inplace=True)
C:\Users\rake0\AppData\Local\Temp\ipykernel_24140\4274336270.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Company Age'].fillna(value=0,inplace=True)

In [2472]:
df['Company Age'].isna().sum()

0

In [2474]:
def dtypeint2(df):
    l1 = ['Salaries', 'Total Interviews', 'Total Jobs', 'Company Age'] #'Founded Year', 'Company Age'
    for i in l1:
        df[i] = df[i].astype('int')

In [2476]:
dtypeint2(df)

In [2479]:
df

,Title,Reviews,Ratings,Company Type,Salaries,Total Interviews,Total Jobs,Founded Year,Company Age,Websites
0,TCS,93700,3.7,IT Services & Consulting,890000,10700,177,1996.0,29,tcs.com
1,Accenture,59300,3.8,IT Services & Consulting,590000,8400,8800,1989.0,36,accenture.com
2,Wipro,55100,3.7,IT Services & Consulting,450000,5800,4100,1945.0,80,careers.wipro.com
3,Cognizant,52400,3.7,IT Services & Consulting,570000,5700,204,1994.0,31,cognizant.com
4,Capgemini,43900,3.7,IT Services & Consulting,440000,4900,2000,1967.0,58,capgemini.com
...,...,...,...,...,...,...,...,...,...,...
495,Infinite Computer Solutions,1600,3.4,IT Services & Consulting,12700,150,185,2001.0,24,infinite.com
496,Philips,1600,3.8,Consumer Electronics & Appliances,10300,160,119,1930.0,95,philips.com
497,Dr Lal PathLabs,1600,4.2,Healthcare,4400,130,58,1949.0,76,lalpathlabs.com
498,Honeywell Automation,1600,3.8,Industrial Automation,11400,104,1,1906.0,119,honeywell.com
499,Nuvoco Vistas,1600,4.1,Building Material,6200,99,20,2014.0,11,nuvoco.com

In [2482]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             500 non-null    object
 1   Reviews           500 non-null    int32
 2   Ratings           500 non-null    float64
 3   Company Type      478 non-null    object
 4   Salaries          500 non-null    int32
 5   Total Interviews  500 non-null    int32
 6   Total Jobs        500 non-null    int32
 7   Founded Year      500 non-null    object
 8   Company Age       500 non-null    int32
 9   Websites          500 non-null    object
dtypes: float64(1), int32(5), object(4)
memory usage: 29.4+ KB

In [2484]:
df[df['Company Type'].isna()]

,Title,Reviews,Ratings,Company Type,Salaries,Total Interviews,Total Jobs,Founded Year,Company Age,Websites
45,Startek,7900,3.1,NaN,23700,490,58,2017.0,8,startek.com
83,Ekart Logistics,5600,3.9,NaN,14200,319,1,2009.0,16,ekartlogistics.com
174,Macleods Pharmaceuticals,3400,3.6,NaN,14900,210,12,1986.0,39,macleodspharma.com
210,Cogent E Services,3000,3.3,NaN,9500,246,2,2004.0,21,cogenteservices.com
264,Amazon Transportation Services,2600,4.2,NaN,7600,229,0,2012.0,13,amazon.in
279,I Process Services,2500,3.9,NaN,5400,105,0,2005.0,20,iprocess.inPrimary Industry--Other IndustriesS...
308,Domino's Pizza,2300,3.9,NaN,4200,90,0,1960.0,65,dominos.com
310,XpressBees,2300,3.6,NaN,7700,169,4,2015.0,10,xpressbees.com
321,TVS Supply Chain Solutions,2200,3.8,NaN,8200,136,3,1896.0,129,tvsscs.com
324,McDonald's,2200,4.1,NaN,4700,126,3,1955.0,70,mcdonalds.com
341,Himalaya Wellness,2100,4.1,NaN,5900,116,6,1930.0,95,himalayawellness.in
342,Taj Hotels Resorts and Palaces,2100,4.2,NaN,4700,123,0,1903.0,122,tajhotels.com
372,Delhi Public School,2000,3.9,NaN,5400,114,66,1998.0,27,dpsfamily.orgPrimary Industry--Other Industrie...
376,JCB,2000,3.9,NaN,9000,138,0,1945.0,80,jcb.com
379,Emcure Pharmaceuticals,2000,3.7,NaN,8100,104,42,1983.0,42,emcure.com
381,Radisson Hotels,2000,4.1,NaN,5400,79,131,1909.0,116,radissonhotels.com
414,GVK Emergency Management and Research Institute,1800,3.6,NaN,4400,91,9,2005.0,20,emri.in
416,Renault-Nissan,1800,4.1,NaN,7600,110,0,2007.0,18,alliancernm.com
432,Apollo Pharmacy,1800,3.8,NaN,5800,129,44,1983.0,42,apollopharmacy.in
455,ITC Hotels,1700,4.1,NaN,5400,86,0,1975.0,50,itchotels.in
462,American Broadcasting Company,1600,4.0,NaN,23100,553,17,Not Available,0,abc.comPrimary Industry--Other IndustriesMedia...
466,Henry Harvin Education,1700,3.7,NaN,788,14,38,2015.0,10,henryharvin.com

In [2486]:
df['Company Type'].fillna(value='Unknown',inplace=True)

C:\Users\rake0\AppData\Local\Temp\ipykernel_24140\10851803.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Company Type'].fillna(value='Unknown',inplace=True)

In [2488]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             500 non-null    object
 1   Reviews           500 non-null    int32
 2   Ratings           500 non-null    float64
 3   Company Type      500 non-null    object
 4   Salaries          500 non-null    int32
 5   Total Interviews  500 non-null    int32
 6   Total Jobs        500 non-null    int32
 7   Founded Year      500 non-null    object
 8   Company Age       500 non-null    int32
 9   Websites          500 non-null    object
dtypes: float64(1), int32(5), object(4)
memory usage: 29.4+ KB

In [2490]:
df

,Title,Reviews,Ratings,Company Type,Salaries,Total Interviews,Total Jobs,Founded Year,Company Age,Websites
0,TCS,93700,3.7,IT Services & Consulting,890000,10700,177,1996.0,29,tcs.com
1,Accenture,59300,3.8,IT Services & Consulting,590000,8400,8800,1989.0,36,accenture.com
2,Wipro,55100,3.7,IT Services & Consulting,450000,5800,4100,1945.0,80,careers.wipro.com
3,Cognizant,52400,3.7,IT Services & Consulting,570000,5700,204,1994.0,31,cognizant.com
4,Capgemini,43900,3.7,IT Services & Consulting,440000,4900,2000,1967.0,58,capgemini.com
...,...,...,...,...,...,...,...,...,...,...
495,Infinite Computer Solutions,1600,3.4,IT Services & Consulting,12700,150,185,2001.0,24,infinite.com
496,Philips,1600,3.8,Consumer Electronics & Appliances,10300,160,119,1930.0,95,philips.com
497,Dr Lal PathLabs,1600,4.2,Healthcare,4400,130,58,1949.0,76,lalpathlabs.com
498,Honeywell Automation,1600,3.8,Industrial Automation,11400,104,1,1906.0,119,honeywell.com
499,Nuvoco Vistas,1600,4.1,Building Material,6200,99,20,2014.0,11,nuvoco.com

In [2494]:
def regex1(x):
    txt = x.strip()
    reg = re.findall(r"(^.+\.?\w+\.(?:com|org|in|jobs|net|ntt|bank|ai|abb|barclays|run|tech|ee|biz|live|bnpparibas))\s?",txt)
    return reg[0]

In [2496]:
df['Websites'] = df['Websites'].apply(regex1)

In [2500]:
df['Websites']

0                tcs.com
1          accenture.com
2      careers.wipro.com
3          cognizant.com
4          capgemini.com
             ...
495         infinite.com
496          philips.com
497      lalpathlabs.com
498        honeywell.com
499           nuvoco.com
Name: Websites, Length: 500, dtype: object

In [2506]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             500 non-null    object
 1   Reviews           500 non-null    int32
 2   Ratings           500 non-null    float64
 3   Company Type      500 non-null    object
 4   Salaries          500 non-null    int32
 5   Total Interviews  500 non-null    int32
 6   Total Jobs        500 non-null    int32
 7   Founded Year      500 non-null    object
 8   Company Age       500 non-null    int32
 9   Websites          500 non-null    object
dtypes: float64(1), int32(5), object(4)
memory usage: 29.4+ KB

In [2508]:
df.to_csv("Companies_500_Cleaned.csv",index=False)

In [2492]:
# for i in list(df['Websites']):
#     print(i)
#     print()

tcs.com

accenture.com

careers.wipro.com

cognizant.com

capgemini.com

hdfcbank.com

infosys.com

icicibank.com

hcltech.com

techmahindra.com

genpact.com

teleperformance.comPrimary IndustryBPOOther IndustriesIT Services & Consulting|Software ProductReplay videoView in video summaryTeleperformance is the leading global provider of outsourced Digital Integrated Business Services.Since its 2001 entry into India, Teleperformance leveraged the country’s vast talent pool to offer quality offshore solutions for global brands, and is the designated Center of Excellence (CoE) for Digital CX Services, Back-office, and Transformation Solutions.With an employee strength of 90,000+, India represents the largest multicultural team within Teleperformance, providing world-class services to 210+ clients across different industries.Our High-Tech, High-Touch approach combines the most advanced digital and technology solutions with the human touch to empower world’s leading brands adapt to disruptive digital innovations.Teleperformance in India is recognized among Top 15 Best Workplaces in Asia and is 10 times certified as a Great Place To Work®Mission: We make people's lives simpler, faster, and safer by combining passionate people, the most advanced solutions, and disciplined processes to help companies transform and run better.Vision: We believe that happy employees make happy customers, which, in turn, makes happy clients and happy shareholders. We are therefore inspired to deliver only the best in all that we do.Teleperformance RatingsView allbased on 31k reviewsOverall Rating3.9/5How AmbitionBox ratings work?514.6k45.9k34k21.8k14.8kCategory Ratings3.8Company culture3.8Job security3.8Work-life balance3.8Skill development3.7Salary3.7Work satisfaction3.5PromotionsTeleperformance is rated 3.9 out of 5 stars on AmbitionBox, based on 31k company reviews.This rating reflects an average employee experience, indicating moderate satisfaction with the company’s work culture, benefits, and career growth opportunities. AmbitionBox gathers authentic employee reviews and ratings, making it a trusted platform for job seekers and employees in India.Read moreGender Based Ratings at Teleperformancebased on 29.4k reviews3.7Rated by 9.4k WomenRated 3.6 for Skill development and 3.5 for Work-life balance 4.0Rated by 20k MenRated 3.9 for Work-life balance and 3.9 for Company culture Work Policy at Teleperformance based on 5.7k reviews in last 6 monthsWork from office64%Hybrid25%Permanent work from home11%Teleperformance ReviewsView allTop mentions in Teleperformance ReviewsSalary (4k)Senior Management (3.4k)Work Environment (3.1k)Work Culture (1.8k)Job Security (1.7k)+ 5 moreLikes:Dislikes:No job Security Whenever they want they can hire and after that e...Customer Care Executive in MeerutCustomer Success, Service & Operations - Other2.0 • posted on 17 Apr 2025Likes:Salary - ExcellentSkill development - Excellent+2 moreDislikes:No job Security Whenever they want they can hire and after that e...Job security - Bad+2 moreLikes:International exposure, no one fires you directly unless & until you are an outright BQDislikes:Micromanagement, people just not wanting to work, favouritism, ra...Operations Manager in IndoreOperations1.0 • posted on 17 Apr 2025Likes:International exposure, no one fires you directly unless & until you are an outright BQJob security - ExcellentDislikes:Micromanagement, people just not wanting to work, favouritism, ra...Promotions - Poor+2 moreLikes:Company culture and salary on timeDislikes:In which process i was working there is no Job security(VRM) that...Digital Relationship Manager in Navi MumbaiVoice / Blended5.0 • posted on 16 Apr 2025Likes:Company culture and salary on timeSalary - Excellent+4 moreDislikes:In which process i was working there is no Job security(VRM) that...Likes:NothingDislikes:Lot of pressure. No work life balance. Discrimination between emp...Customer Support Executive in MorindaOther1.0 • posted on 16 Apr 2025Likes:NothingDislikes:Lot of pressure. No work life balance. Discrimination between emp...Salary - Bad+6 moreLikes:Dislikes:Bgv process should be done from before.I am from kolkata and I do...Customer Care Executive in IndoreRetail & B2C Sales1.0 • posted on 14 Apr 2025Dislikes:Bgv process should be done from before.I am from kolkata and I do...Skill development - Bad+5 moreLikes:teleperformance  is my first company where i worked for one year and more. very joyful and is very flexible to work...Dislikes:nothin that dislike to teleperformance.Associate in PuneVoice / Blended5.0 • posted on 13 Apr 2025Likes:teleperformance  is my first company where i worked for one year and more. very joyful and is very flexible to work...Skill development - Excellent+5 moreDislikes:nothin that dislike to teleperformance.Likes:After completing 9 months you can apply for promotions.Dislikes:Internal politics if you are going for promotion, favourite candi...Customer Care Executive in MohaliCustomer Success2.0 • posted on 11 Apr 2025Likes:After completing 9 months you can apply for promotions.Dislikes:Internal politics if you are going for promotion, favourite candi...Salary - Poor+5 moreLikes:I don't like anythingDislikes:It's the worst company, it doesn't provide cab facility to male e...Customer Support Executive in MohaliNon Voice1.0 • posted on 10 Apr 2025Likes:I don't like anythingDislikes:It's the worst company, it doesn't provide cab facility to male e...Salary - Bad+6 moreLikes:Supportive Team Environment: I found the team culture to be collaborative, and my colleagues were always willing to...Dislikes:During my time at Teleperformance Global Services Private Limited...Loan Officer in MumbaiVoice / Blended5.0 • posted on 09 Apr 2025Likes:Supportive Team Environment: I found the team culture to be collaborative, and my colleagues were always willing to...Salary - Excellent+6 moreDislikes:During my time at Teleperformance Global Services Private Limited...Likes:The training part was goodDislikes:They are very unprofessional. They are very lazy. They don’t have...Calling Agent in NoidaCustomer Success1.0 • posted on 09 Apr 2025Likes:The training part was goodDislikes:They are very unprofessional. They are very lazy. They don’t have...Salary - Bad+6 moreCompare Teleperformance with Similar CompaniesTeleperformanceWNSChange CompanyiEnergizerChange CompanyConcentrix CorporationChange CompanyOverall Rating3.9/5based on 31k reviews3.4/5based on 12.5k reviews4.6/5based on 23.4k reviews3.7/5based on 27.4k reviewsHighly Rated forSkill developmentWork-life balanceJob securityNo highly rated categorySkill developmentWork-life balanceSalaryJob securityCritically Rated forNo critically rated categoryPromotionsSalarySkill developmentNo critically rated categoryPromotionsSalary

concentrix.com

axisbank.com

amazon.jobs

jio.com

ienergizer.com Company contact no.8588894888 E-mailinfo@iEnergizer.com

relianceretail.com

ibm.com

ltimindtree.com

hdbfs.com

larsentoubro.com

www2.deloitte.com

kotak.com

ril.com

byjus.com

myvi.in

airtel.in

wns.com

tatamotors.com

aubank.in

indusind.com

flipkart.com

ey.com

idfcfirstbank.com

dxc.com

infosysbpm.com

mahindra.com

bajajfinserv.in

pwc.com

hdfclife.com

conneqtcorp.com

mphasis.comPrimary IndustryIT Services & ConsultingOther IndustriesFinancial Services|Hardware & Networking|Insurance|Emerging TechnologiesReplay videoView in video summaryMphasis’ purpose is to be the “Driver in Driverless Car” for Global Enterprises by applying next-generation design, architecture and engineering services, to deliver scalable and sustainable software and technology solutions. Customer centricity is foundational to Mphasis and is reflected in the Mphasis’Front2BackTM Transformation approach. Front2BackTM uses the exponential power of cloud and cognitive to provide hyper-personalized (C=X2C2TM=1) digital experience to clients and their end customers. Mphasis’ Service Transformation approach helps ‘shrink the core’ through the application of digital technologies across legacy environments within an enterprise, enabling businesses to stay ahead in a changing world. Mphasis’ core reference architectures and tools, speed and innovation with domain expertise and specialization, combined with an integrated sustainability and purpose-led approach across its operations and solutions are key to building strong relationships with marquee clients.Mphasis RatingsView allbased on 8.7k reviewsOverall Rating3.4/5How AmbitionBox ratings work?52.7k42.5k31.7k271711.1kCategory Ratings3.5Work-life balance3.4Job security3.3Company culture3.3Skill development3.1Work satisfaction2.8Salary2.5PromotionsMphasis is rated 3.4 out of 5 stars on AmbitionBox, based on 8.7k company reviews.This rating reflects an average employee experience, indicating moderate satisfaction with the company’s work culture, benefits, and career growth opportunities. AmbitionBox gathers authentic employee reviews and ratings, making it a trusted platform for job seekers and employees in India.Read moreGender Based Ratings at Mphasisbased on 8.3k reviews3.5Rated by 2.5k WomenRated 3.6 for Work-life balance and 3.5 for Job security 3.3Rated by 5.8k MenRated 3.5 for Work-life balance and 3.4 for Job security Work Policy at Mphasis based on 1.3k reviews in last 6 monthsHybrid54%Work from office38%Permanent work from home8%Mphasis ReviewsView allTop mentions in Mphasis ReviewsSalary (1.6k)Work Life Balance (967)Appraisal (953)Job Security (883)Senior Management (826)+ 5 moreLikes:Company is never been good or bad it's the people who works there makes the environment good or bad. Some managers...Dislikes:Salary is the biggest minus point if you show your loyalty and st...Project Management Lead in Bangalore / BengaluruOperations3.0 • posted on 16 Apr 2025Likes:Company is never been good or bad it's the people who works there makes the environment good or bad. Some managers...Dislikes:Salary is the biggest minus point if you show your loyalty and st...Salary - PoorLikes:The company has a good work life balance and culture. It also depends on the project which you work for. Work from...Dislikes:Compensation structure is very bad compared to other companies. P...Delivery Software Engineer in Bangalore / BengaluruSoftware Development3.0 • posted on 16 Apr 2025Likes:The company has a good work life balance and culture. It also depends on the project which you work for. Work from...Job security - Excellent+1 moreDislikes:Compensation structure is very bad compared to other companies. P...Salary - Poor+2 moreLikes:I got good colleagues who are friendly and always ready to help.Dislikes:They hired me saying it's hybrid module but since you are new you...Senior Analyst in PuneFinance3.0 • posted on 15 Apr 2025Likes:I got good colleagues who are friendly and always ready to help.Promotions - GoodDislikes:They hired me saying it's hybrid module but since you are new you...Skill development - Poor+2 moreLikes:Nothing much to like. They dont have relationship with clients. Just sending consultants to clients to fill the req...Dislikes:No job security. They dont help in getting projects. Bench meetin...Project Lead in Hyderabad / SecunderabadData Science & Machine Learning1.0 • posted on 07 Apr 2025Likes:Nothing much to like. They dont have relationship with clients. Just sending consultants to clients to fill the req...Dislikes:No job security. They dont help in getting projects. Bench meetin...Salary - Poor+6 moreLikes:Mphasis Pune is a great place to start your career as a fresher because there are ample of new opportunities to exp...Dislikes:What I dislike about this place is I am not working there anymore...Service Desk Associate in PuneCustomer Success5.0 • posted on 06 Apr 2025Likes:Mphasis Pune is a great place to start your career as a fresher because there are ample of new opportunities to exp...Salary - Excellent+6 moreDislikes:What I dislike about this place is I am not working there anymore...Likes:NaDislikes:Worst management and manager's ever seen in my career no proper k...Senior Associate in PuneInvestment Banking, Private Equity & VC1.0 • posted on 05 Apr 2025Likes:NaDislikes:Worst management and manager's ever seen in my career no proper k...Salary - Bad+6 moreLikes:Mphasis is good place for taking experience on the profileDislikes:Mphasis pvt Ltd is one the most undarated company which is very t...Senior Quality Analyst in PunePayroll & Transactions1.0 • posted on 29 Mar 2025Likes:Mphasis is good place for taking experience on the profileJob security - ExcellentDislikes:Mphasis pvt Ltd is one the most undarated company which is very t...Salary - Bad+5 moreLikes:Work load is balanced. Sufficient team to manage work.Dislikes:No salary hikes from last 5 years. No promotions. If any then dry...Data Engineer in Bangalore / BengaluruData Science & Machine Learning2.0 • posted on 23 Mar 2025Likes:Work load is balanced. Sufficient team to manage work.Work-life balance - GoodDislikes:No salary hikes from last 5 years. No promotions. If any then dry...Salary - Poor+4 moreLikes:Dislikes:Everything, absolutely no pay hikes and promotions, no bonus, no...Technical Support Engineer in PuneIT Support1.0 • posted on 20 Mar 2025Dislikes:Everything, absolutely no pay hikes and promotions, no bonus, no...Salary - Bad+6 moreLikes:It depends on the team we work with, if the team manager or lead is chill and doesn't bother much about micro manag...Dislikes:If the micro management is high, even with WFH you'll struggle an...Automation Test Engineer in Bangalore / BengaluruQuality Assurance and Testing3.0 • posted on 16 Mar 2025Likes:It depends on the team we work with, if the team manager or lead is chill and doesn't bother much about micro manag...Promotions - GoodDislikes:If the micro management is high, even with WFH you'll struggle an...Skill development - Poor+4 moreCompare Mphasis with Similar CompaniesMphasisLTIMindtreeChange CompanySutherland Global ServicesChange CompanyDXC TechnologyChange CompanyOverall Rating3.4/5based on 8.7k reviews3.7/5based on 21.9k reviews3.5/5based on 7.3k reviews3.7/5based on 10.4k reviewsHighly Rated forNo highly rated categoryWork-life balanceNo highly rated categoryWork-life balanceCritically Rated forPromotionsSalaryWork satisfactionPromotionsSalaryPromotionsSalarySkill developmentPromotionsSalary

bandhanbank.com

yesbank.in

startek.com

paytm.com

tatasteel.com

asianpaints.com

quesscorp.com

marutisuzuki.com

ultratechcement.com

samsung.com

sutherlandglobal.com

shriramfinance.in

ericsson.com

exlservice.com

cipla.com

muthootfincorp.com

joinhgs.com

drreddys.com

bajajfinserv.in

wellsfargojobs.com E-mailprivacy.emea@wellsfargo.com

amazon.com

iciciprulife.com

jpmorganchase.com

delhivery.com

hul.co.in


In [2502]:
# for i in list(df['Websites']):
#     print(i)
#     print()

tcs.com

accenture.com

careers.wipro.com

cognizant.com

capgemini.com

hdfcbank.com

infosys.com

icicibank.com

hcltech.com

techmahindra.com

genpact.com

teleperformance.com

concentrix.com

axisbank.com

amazon.jobs

jio.com

ienergizer.com Company contact no.8588894888 E-mailinfo@iEnergizer.com

relianceretail.com

ibm.com

ltimindtree.com

hdbfs.com

larsentoubro.com

www2.deloitte.com

kotak.com

ril.com

byjus.com

myvi.in

airtel.in

wns.com

tatamotors.com

aubank.in

indusind.com

flipkart.com

ey.com

idfcfirstbank.com

dxc.com

infosysbpm.com

mahindra.com

bajajfinserv.in

pwc.com

hdfclife.com

conneqtcorp.com

mphasis.com

bandhanbank.com

yesbank.in

startek.com

paytm.com

tatasteel.com

asianpaints.com

quesscorp.com

marutisuzuki.com

ultratechcement.com

samsung.com

sutherlandglobal.com

shriramfinance.in

ericsson.com

exlservice.com

cipla.com

muthootfincorp.com

joinhgs.com

drreddys.com

bajajfinserv.in

wellsfargojobs.com E-mailprivacy.emea@wellsfargo.com

amazon.com

iciciprulife.com

jpmorganchase.com

delhivery.com

hul.co.in

janabank.com

optum.in

lupin.com

hexaware.com Company contact no.2267919595 E-mailmarketing@hexaware.com

lntecc.com

zyduslife.com

equitasbank.com

jsw.in

sunpharma.com Company contact no.2243244324 E-mailjanet.metz@sunpharma.com

itcportal.com

kpmg.com

fisglobal.com

hcl.com

maxlifeinsurance.com

ujjivansfb.in

ekartlogistics.com

tataprojects.com Company contact no.2267402900 E-mailtpl@tataprojects.com

oracle.com

indianarmy.nic.in

iifl.com

meil.in

muthootfinance.com

eclerx.com

udaan.com

omegahms.com

bajajallianzlife.com

jll.co.in

Ltts.com

virtusa.com

indiamart.com

coforge.com

hsbc.com

siemens.com

aurobindo.com

shapoorjipallonji.com

sc.com

firstsource.com

dmartindia.com

cgi.com

cholamandalam.com

globallogic.com

apollohospitals.com

ashokleyland.com

icicilombard.com

bigbasket.com Company contact no.8601231000 E-mailcustomerservice@bigbasket.com

cyient.com

bosch-softwaretechnologies.com

ust.com

citigroup.com

heromotocorp.com

mahindrafinance.com

justdial.com

eviden.com

vivo.com

smfgindiacredit.com

homecredit.co.in

manappuram.com

bny.com

atos.net

tvsmotor.com

iqvia.com

swiggy.com

sbicard.com

nagarro.com

oppo.com

persistent.com Company contact no.2067462084 E-mailinfo@persistent.com

kalpataruprojects.com

amdocs.com

bosch.com

cbre.co.in

global.ntt

sbi.co.in

hpe.com

mahindralogistics.com

jbmgroup.com

sbilife.co.in

schneiderelectric.com

dell.com

policybazaar.com

ecomexpress.in

ncclimited.com

piramalfinance.com

kecrpg.com

abfrl.com

hyundai.com

varunbeverages.com

cars24.com

randstad.in

oyorooms.com

ey.com

bajajauto.com

db.com

ltfinance.com

rcom.co.in

intaspharma.com

itcinfotech.com

teamleasegroup.com

r1rcm.com

tatacommunications.com

havells.com

accesshealthcare.com

royalenfield.com

johndeere.com

hetero.com

lg.com

thermaxglobal.com

macleodspharma.com

aakash.ac.in

hdfcergo.com

tataaia.com

utkarsh.bank

careers.publicissapient.com Career pagehttps://careers.publicissapient.com

dcbbank.com

cummins.com

vecv.in

pvrcinemas.com

viatris.com

bergerpaints.com

carelonglobal.in

godrej.com

motherson.com

lenskart.com

subros.com

pidilite.com

in.adp.com

alembicpharmaceuticals.com

americanexpress.com

bankofamerica.com

abbott.com

sodexo.com

jindalsteel.com

hindalco.com

bel-india.in

rblbank.com

jubilantfoodworks.com

kogta.in

ril.com

iocl.com

futuregroup.in

birlasoft.com

synechron.com

escortskubota.com

cogenteservices.com

maersk.com

dabur.com

marpu.org

reliancedigital.in

johnsoncontrols.in

corporate.ford.com

us.nttdata.com Career pagehttps://us.nttdata.com/en/careers Follow us on naukrihttps://www.naukri.com

statestreet.com

glenmarkpharma.com

alkemlabs.com

ipca.com

247.ai

ubs.com

pnbmetlife.com

aarti-industries.com

vishalmegamart.com

kotaklife.com

kyndryl.com Career pagehttps://www.kyndryl.com/in/en/careers Follow us on naukrihttps://www.naukri.com/kyndryl-overview-5462642 Company contact no.9980851851 E-mailinquiry@kyndryl.com

jkcement.com

honda2wheelersindia.com

kpit.com

mrftyres.com

indianairforce.nic.in

hccb.in

harman.com

motilaloswalgroup.com

dtdc.in

igtsolutions.com

lifeinsurance.adityabirlacapital.com

reliancenipponlife.com

global.abb

conduent.com

ceat.com

natwestgroup.com

squareyards.com

gebbs.com

goindigo.in

grasim.com

whitehatjr.com

unitedhealthgroup.com

alstom.com

amns.in

rsplgroup.com

tatacapital.com

cmsitservices.com

maxhealthcare.in

tatatechnologies.com

tataaig.com

pepsicoindia.co.in

spglobal.com

titancompany.in

varroc.com

unominda.com

amazon.in

upl-ltd.com

acclimited.com

zensar.com

torrentpharma.com

croma.com

mankindpharma.com

walmart.com

afcons.com

shoppersstop.com

bajajallianz.com

globalsolutioncenter.societegenerale.in

home.barclays

dilipbuildcon.co.in

tvscredit.com

iprocess.in

quest-global.com

hdfcsales.com

capita.com

flex.com

medicoverhospitals.in

nokia.com

msnlabs.com

elastic.run

fiserv.com

phonepe.com

apollotyres.com

nestle.in

ikshealth.com

statestreet.com

gati.com

suzlon.com

eternal.com

landmarkgroup.com

agshealth.com

idfcbharat.com

indiabullshomeloans.com

bluedart.com

blackbuck.com

fujitsu.com

dsgroup.com

parashospitals.com

yazaki-group.com

shreecement.com

dominos.com

tataelxsi.com

xpressbees.com

bajajelectricals.com

britannia.co.in

microlabsltd.com

kpmg.com

stl.tech

exideindustries.com

g4s.com

industowers.com

kochartech.com

axisdirect.in

tvsscs.com

voltas.com

capgemini.com

mcdonalds.com

vvdntech.com

kfintech.com

jslstainless.com

zs.com

patanjaliayurved.net

allsectech.com

blinkit.com

fortishealthcare.com

dalmiacement.com

tafe.com

srf.com

shell.in

bluestarindia.com

actcorp.in

nobroker.in

movate.com

himalayawellness.in

tajhotels.com

sonalika.com

huawei.com

nerolac.com

ajantapharma.com

vmartretail.com

datamatics.com

foundever.com

lavamobiles.com

infoedge.in

mahindrahomefinance.com

marutisuzuki.com

akums.in

simplexinfra.com

lifestylestores.com

adityabirla.com

3i-infotech.com

magicbricks.com

unacademy.com

cholainsurance.com

linktr.ee

esafbank.com

clubmahindra.com

bt.com

cybage.com

olacabs.com

life.myntra.com

icicisecurities.com

parleagro.com

intellectdesign.com

dpsfamily.org

eurekaforbes.com

careinsurance.com

syngeneintl.com

jcb.com

syntelinc.com

biocon.com

emcure.com

intouchcx.com

radissonhotels.com

xoriant.com Company contact no.2230511000 E-mailcareers@xoriant.com

nokia.com

canarahsbclife.com

starhealth.in

dbs.com

extramarks.com

adanipower.com

cloudninecare.com

planetspark.in

bfil.co.in

cadilapharma.com

ninjacart.in

indianrailways.gov.in

sobha.com

gsk-india.com

olaelectric.com

herofincorp.com

bhel.com

soprasteria.com Company contact no.0140672929 E-mailcontact-corp@soprasteria.com

photon.in

sagilityhealth.com

straive.com

cisco.com

aavas.in

licindia.in

whirlpoolcorp.com

group.bureauveritas.com

tataadvancedsystems.com

upgrad.com

rntbci.in

bharti-axalife.com

shahi.co.in

emri.in

nivabupa.com

alliancernm.com

raymondlifestyle.com

pfizer.com

endurancegroup.com

lodhagroup.com

kia.com

ambujacement.com

rmsi.com

hsbc.co.in

exlindia.com

forcemotors.com

lauruslabs.com

reliancetrends.com

panasonic.com

valuelabs.com

meesho.com

apollopharmacy.in

bankofbaroda.com

camsonline.com

coromandel.biz

sencogoldanddiamonds.com

adityabirlacapital.com

allstate.com

poonawallafincorp.com

microsoft.com

sifytechnologies.com

tce.co.in

cargill.co.in

adaniwilmar.com

delphitvs.com

sbisecurities.in

brakesindia.com

futureretail.co.in

general.futuregenerali.in

bharatpetroleum.com

sap.com

pw.live

sudlife.in

sbigeneral.in

itchotels.in

citiustech.com

googleoperationscenter.com

sparkminda.com

tmf.co.in

adani.com

yash.com

abc.com

dhaniloansandservices.com

kent.co.in

powermechprojects.com

henryharvin.com

saint-gobain.com

crisil.com

kotaksecurities.com

aecom.com Company contact no.9727881000 E-mailtalismanSaber2017@aecom.com

anandgroupindia.com

lnthydrocarbon.com

teamcomputers.com

jktyre.com

novartis.com

mbrdi.co.in Career pagehttps://jobs.mercedes-benz.com/en?en=&parentorganization=[140]&positionlocation.country=[390] Company contact no.8061506600 E-mailmbrdi_ehs@mercedes-benz.com

idbi.com

group.bnpparibas

ncrvoyix.com

parleproducts.com

sterlingandwilson.com

taskus.com

lucas-tvs.com

reliancegeneral.co.in

microland.com

uflexltd.com Company contact no.01204012345 E-mailenquiry@uflexltd.com

paisabazaar.com

thomsonreuters.com

kalyanjewellers.net

firstcry.com

sgs.com

daikin.com

morganstanley.com

hal-india.co.in

infinite.com

philips.com

lalpathlabs.com

honeywell.com

nuvoco.com

In [ ]:
#        (^\w+\.?\w+?\.\w+)\s?

In [ ]:
#        (^.+\.?\w+\.(?:com|org|in|jobs|net|ntt|bank|ai|abb|barclays|run|tech|ee|biz|live|bnpparibas))\s?   # best one

In [60]:
'L' in '5.9L'

True

In [20]:
10.7*1000

10700.0

In [22]:
4.5*100000

450000.0

In [24]:
93.7*1000

93700.0

In [587]:
df['Salaries'][15].replace('k','')

'62.2'

In [619]:
df['Salaries'].iloc[2].replace('L','')

'4.5'

In [1299]:
l = ["153K","1.4L"]

In [938]:
for i in l:
    if "K"  in i:
        print(int(i.replace("K","")) *1000)
    else:
        print(float(i.replace("L","")) *100000)

153000
140000.0

In [954]:
for i in df['Salaries']:
    #print(i)
    n = 0
    if "k" in i:
        df['Salaries'] = int(i.replace("k",""))*1000

91.5k
99.5k
62.2k
22.8k
66.9k
50k
69.6k
82.5k
68.6k
58.6k
53.2k
46.7k
63.3k
41.1k
26.2k
49.1k
49.2k
44.9k
74.7k
67.1k
37.3k
27.4k
93.3k
31.1k
27k
69k
23.4k
42.4k
23.7k
32.3k
30.5k
23k
29k
25.3k
22.6k
26.3k
30.8k
13.7k
42.2k
40.4k
24.5k
8.4k
22.8k
24.4k
21.4k
51.1k
33k
21.4k
73.6k
19.5k
21.4k
14.8k
40.5k
22.4k
48.3k
18.7k
18.9k
12.2k
27.2k
21.9k
22.7k
54.2k
38k
48.7k
18.3k
12.4k
14.2k
20.3k
57.3k
9.4k
14.5k
16.7k
12.2k
29.1k
17k
23.3k
16k
21.6k
38.8k
53.1k
42k
19k
37.5k
30.9k
21.5k
14.9k
39.8k
22.5k
16k
43.4k
11.4k
36.2k
15.9k
18.1k
18.8k
17.6k
26.4k
36.5k
36.8k
44.9k
14.9k
11.2k
14.7k
29.8k
13.3k
10.6k
10.4k
8.3k
28.8k
32k
14.9k
28.2k
21k
15.2k
27.9k
12.3k
38.7k
12.6k
35.7k
20.1k
17.3k
29k
11k
27k
13.4k
13.8k
11k
21.9k
27.7k
15.2k
9.5k
10.8k
9k
12k
12.4k
12.9k
10.9k
14.2k
15.3k
20k
34.3k
13.6k
31.9k
11k
10.7k
16.2k
28.3k
15.3k
18.9k
23.1k
12.9k
21.6k
13.8k
14.8k
14.5k
10.5k
12.2k
14.9k
12.4k
11.6k
12.8k
10k
27.4k
9.4k
15.1k
13.1k
9.4k
13.8k
9k
25k
15.4k
12.6k
11.1k
12.2k
10.1k
20.3k
14.2k
21.6k
25.5k
11.2k
9.7k
14.2k
10.7k
12k
17k
8.4k
1.7k
6.8k
7.8k
9.3k
28.7k
27.4k
12.1k
9.5k
17.5k
8.4k
7.9k
16.3k
14.5k
26.1k
27.5k
11.4k
9.3k
11.1k
13.3k
29.1k
7.6k
13.8k
6.3k
11.6k
21.5k
8.9k
10.9k
21k
11.5k
5.1k
7.3k
23.6k
10.5k
8.5k
12.4k
9.1k
8.3k
16k
17.6k
12.3k
19.6k
8.7k
11.2k
12.9k
10.8k
9.5k
17.1k
13k
10.1k
9k
9.6k
10k
9.6k
20.5k
10.7k
11.4k
18.1k
8.9k
8.9k
9.7k
7.6k
10.9k
9.3k
25.3k
10k
7.7k
8.6k
18k
8.1k
7.1k
8.9k
20.7k
25.5k
8.1k
6.6k
5.4k
19k
8.1k
13.7k
16.6k
3.2k
15.2k
8.5k
6.3k
18.4k
10.6k
9.5k
9.3k
10.1k
15.9k
5.6k
7.6k
13.1k
9.2k
10.6k
4.6k
7.3k
6.4k
6.5k
16.3k
6.8k
3k
8.2k
9.3k
4.2k
19.6k
7.7k
7.7k
7.7k
9.6k
20.1k
10.2k
8k
4.9k
8.2k
5.3k
3.9k
8.2k
8.3k
16.7k
4.7k
11.8k
10k
10k
16.8k
6.3k
7.1k
9.5k
7.4k
8.2k
8.2k
8.2k
13.3k
9.2k
7.5k
9.4k
13.9k
5.9k
4.7k
8.5k
9.9k
7k
8.6k
4.3k
11.6k
7.7k
4.7k
11.2k
4.9k
7.3k
6k
5.6k
7k
10.1k
10.8k
4.3k
9.7k
5.8k
12.1k
6.6k
5.9k
10.7k
16.8k
10.6k
9.9k
8.9k
6.4k
12k
5.4k
5.5k
8k
11.6k
9k
8.7k
11.6k
8.1k
8.4k
5.4k
11.1k
11.7k
6.3k
8.5k
12.4k
8k
8.2k
2.6k
3k
4.2k
7.3k
5.7k
3.5k
8k
5.3k
7.7k
4.9k
5.2k
13.5k
6.9k
8k
9.1k
17.7k
5.8k
4.3k
8k
7.7k
10.7k
8.3k
13.8k
5.2k
6.7k
4.4k
7.5k
7.6k
6.8k
5.7k
7.5k
8k
7.5k
8k
6k
9.1k
11.8k
7.8k
6.9k
4.4k
6k
15.1k
7.6k
5.8k
6.3k
7.7k
7k
1.3k
8.1k
11.2k
5.1k
22.8k
9.5k
8.1k
7.7k
6.4k
5.5k
6k
6.7k
5.2k
6.6k
6.6k
15.5k
5.6k
4.9k
6.2k
5.4k
12.9k
20.7k
6.4k
4.8k
8.9k
15.6k
23.1k
4.9k
4.6k
6.3k
10.1k
11.6k
8.9k
6.3k
5.6k
8.1k
8.1k
6.6k
8.9k
15.7k
5.7k
14.9k
8.5k
3.6k
7.6k
7.2k
5.8k
6.9k
11k
6.6k
6.7k
10.3k
1.4k
8.3k
6k
6.7k
21.6k
4.2k
12.7k
10.3k
4.4k
11.4k
6.2k

In [2384]:
# print(list(df['Total Interviews']))

In [2386]:
# print(list(df['Salaries']))

In [1088]:
df

,Title,Reviews,Ratings,Company Type,Salaries,Total Interviews,Total Jobs,Founded Year,Company Age,Websites
0,TCS,93.7k,3.7,IT Services & Consulting,8.9L,10.7k,177,1996.0,29.0,tcs.com
1,Accenture,59.3k,3.8,IT Services & Consulting,5.9L,8.4k,8.8k,1989.0,36.0,accenture.com
2,Wipro,55.1k,3.7,IT Services & Consulting,4.5L,5.8k,4.1k,1945.0,80.0,careers.wipro.com
3,Cognizant,52.4k,3.7,IT Services & Consulting,5.7L,5.7k,204,1994.0,31.0,cognizant.com
4,Capgemini,43.9k,3.7,IT Services & Consulting,4.4L,4.9k,2k,1967.0,58.0,capgemini.com
...,...,...,...,...,...,...,...,...,...,...
495,Infinite Computer Solutions,1.6k,3.4,IT Services & Consulting,12.7k,150,185,2001.0,24.0,infinite.com
496,Philips,1.6k,3.8,Consumer Electronics & Appliances,10.3k,160,119,1930.0,95.0,philips.com
497,Dr Lal PathLabs,1.6k,4.2,Healthcare,4.4k,130,58,1949.0,76.0,lalpathlabs.com
498,Honeywell Automation,1.6k,3.8,Industrial Automation,11.4k,104,1,1906.0,119.0,honeywell.com
499,Nuvoco Vistas,1.6k,4.1,Building Material,6.2k,99,20,2014.0,11.0,nuvoco.com

In [1319]:
# df["Total Interviews"].apply(sal)

0      10700.0
1       8400.0
2       5800.0
3       5700.0
4       4900.0
        ...
495      150.0
496      160.0
497      130.0
498      104.0
499       99.0
Name: Total Interviews, Length: 500, dtype: float64

In [1315]:
def sal(j):
    if 'k' in j:
        return float(j.replace('k',''))*1000
    elif 'L' in j:
        return float(j.replace('L',''))*100000
    else:
        return float(j)

In [1283]:
def interv(j):
    if 'k' in j:
        return float(j.replace('k',''))*1000
    elif 'L' in j:
        return float(j.replace('L',''))*100000
    else:
        return float(j)

In [1285]:
def jobs(j):
    if 'k' in j:
        return float(j.replace('k',''))*1000
    # elif 'L' in j:
    #     return float(j.replace('L',''))*100000
    else:
        return float(j)

In [1287]:
sal = [sal(j) for j in list(df['Salaries'])]
tint = [interv(j) for j in list(df['Total Interviews'])]
job = [jobs(j) for j in list(df['Total Jobs'])]

TypeError: argument of type 'float' is not iterable

In [1310]:
df["Total Jobs"].isna().sum()

58

In [1289]:
sal

[890000.0,
 590000.0,
 450000.0,
 570000.0,
 440000.00000000006,
 140000.0,
 480000.0,
 150000.0,
 340000.0,
 270000.0,
 210000.0,
 91500.0,
 120000.0,
 99500.0,
 130000.0,
 62200.0,
 22800.0,
 66900.0,
 200000.0,
 180000.0,
 50000.0,
 69600.0,
 190000.0,
 82500.0,
 68600.0,
 58600.0,
 53200.0,
 46700.0,
 63300.0,
 41100.0,
 26200.0,
 49100.0,
 49200.0,
 120000.0,
 44900.0,
 74700.0,
 67100.0,
 37300.0,
 27400.0,
 93300.0,
 31100.0,
 27000.0,
 69000.0,
 23400.0,
 42400.0,
 23700.0,
 32299.999999999996,
 30500.0,
 23000.0,
 29000.0,
 25300.0,
 22600.0,
 26300.0,
 30800.0,
 13700.0,
 42200.0,
 40400.0,
 24500.0,
 8400.0,
 22800.0,
 24400.0,
 21400.0,
 51100.0,
 33000.0,
 21400.0,
 73600.0,
 19500.0,
 21400.0,
 14800.0,
 40500.0,
 22400.0,
 48300.0,
 18700.0,
 18900.0,
 12200.0,
 27200.0,
 21900.0,
 22700.0,
 54200.0,
 38000.0,
 48700.0,
 18300.0,
 12400.0,
 14200.0,
 20300.0,
 57300.0,
 9400.0,
 14500.0,
 16700.0,
 12200.0,
 29100.0,
 17000.0,
 23300.0,
 16000.0,
 21600.0,
 38800.0,
 53100.0,
 42000.0,
 19000.0,
 37500.0,
 30900.0,
 21500.0,
 14900.0,
 39800.0,
 22500.0,
 16000.0,
 43400.0,
 11400.0,
 36200.0,
 15900.0,
 18100.0,
 18800.0,
 17600.0,
 26400.0,
 36500.0,
 36800.0,
 44900.0,
 14900.0,
 11200.0,
 14700.0,
 29800.0,
 13300.0,
 10600.0,
 10400.0,
 8300.0,
 28800.0,
 32000.0,
 14900.0,
 28200.0,
 21000.0,
 15200.0,
 27900.0,
 12300.0,
 38700.0,
 12600.0,
 35700.0,
 20100.0,
 17300.0,
 29000.0,
 11000.0,
 27000.0,
 13400.0,
 13800.0,
 11000.0,
 21900.0,
 27700.0,
 15200.0,
 9500.0,
 10800.0,
 9000.0,
 12000.0,
 12400.0,
 12900.0,
 10900.0,
 14200.0,
 15300.0,
 20000.0,
 34300.0,
 13600.0,
 31900.0,
 11000.0,
 10700.0,
 16200.0,
 28300.0,
 15300.0,
 18900.0,
 23100.0,
 12900.0,
 21600.0,
 13800.0,
 14800.0,
 14500.0,
 10500.0,
 12200.0,
 14900.0,
 12400.0,
 11600.0,
 12800.0,
 10000.0,
 27400.0,
 9400.0,
 15100.0,
 13100.0,
 9400.0,
 13800.0,
 9000.0,
 25000.0,
 15400.0,
 12600.0,
 11100.0,
 12200.0,
 10100.0,
 20300.0,
 14200.0,
 21600.0,
 25500.0,
 11200.0,
 9700.0,
 14200.0,
 10700.0,
 12000.0,
 17000.0,
 8400.0,
 1700.0,
 6800.0,
 7800.0,
 9300.0,
 28700.0,
 27400.0,
 12100.0,
 9500.0,
 17500.0,
 8400.0,
 50.0,
 7900.0,
 16300.0,
 14500.0,
 26100.0,
 27500.0,
 11400.0,
 9300.0,
 11100.0,
 13300.0,
 29100.0,
 7600.0,
 13800.0,
 6300.0,
 11600.0,
 21500.0,
 8900.0,
 10900.0,
 21000.0,
 11500.0,
 5100.0,
 7300.0,
 23600.0,
 10500.0,
 8500.0,
 12400.0,
 9100.0,
 8300.0,
 16000.0,
 17600.0,
 12300.0,
 19600.0,
 8700.0,
 11200.0,
 12900.0,
 10800.0,
 9500.0,
 17100.0,
 13000.0,
 10100.0,
 9000.0,
 9600.0,
 10000.0,
 9600.0,
 20500.0,
 10700.0,
 11400.0,
 18100.0,
 8900.0,
 8900.0,
 9700.0,
 7600.0,
 10900.0,
 9300.0,
 25300.0,
 10000.0,
 7700.0,
 8600.0,
 18000.0,
 8100.0,
 7100.0,
 8900.0,
 20700.0,
 25500.0,
 8100.0,
 6600.0,
 5400.0,
 19000.0,
 8100.0,
 13700.0,
 16600.0,
 3200.0,
 15200.0,
 8500.0,
 6300.0,
 18400.0,
 10600.0,
 9500.0,
 9300.0,
 10100.0,
 15900.0,
 5600.0,
 7600.0,
 13100.0,
 9200.0,
 10600.0,
 4600.0,
 7300.0,
 6400.0,
 6500.0,
 16300.0,
 6800.0,
 3000.0,
 8200.0,
 9300.0,
 4200.0,
 19600.0,
 7700.0,
 7700.0,
 7700.0,
 9600.0,
 20100.0,
 10200.0,
 8000.0,
 4900.0,
 8200.0,
 5300.0,
 3900.0,
 8200.0,
 8300.0,
 16700.0,
 4700.0,
 11800.0,
 10000.0,
 10000.0,
 16800.0,
 6300.0,
 7100.0,
 9500.0,
 7400.0,
 8200.0,
 8200.0,
 8200.0,
 13300.0,
 9200.0,
 7500.0,
 9400.0,
 13900.0,
 5900.0,
 4700.0,
 8500.0,
 9900.0,
 7000.0,
 8600.0,
 4300.0,
 11600.0,
 7700.0,
 4700.0,
 11200.0,
 4900.0,
 7300.0,
 6000.0,
 5600.0,
 7000.0,
 10100.0,
 10800.0,
 4300.0,
 9700.0,
 5800.0,
 12100.0,
 6600.0,
 5900.0,
 10700.0,
 16800.0,
 10600.0,
 9900.0,
 8900.0,
 6400.0,
 12000.0,
 5400.0,
 5500.0,
 8000.0,
 11600.0,
 9000.0,
 8700.0,
 11600.0,
 8100.0,
 8400.0,
 5400.0,
 11100.0,
 11700.0,
 6300.0,
 8500.0,
 12400.0,
 8000.0,
 8200.0,
 2600.0,
 3000.0,
 4200.0,
 7300.0,
 5700.0,
 3500.0,
 8000.0,
 5300.0,
 7700.0,
 4900.0,
 5200.0,
 13500.0,
 6900.0,
 8000.0,
 9100.0,
 17700.0,
 5800.0,
 4300.0,
 8000.0,
 7700.0,
 10700.0,
 8300.0,
 13800.0,
 5200.0,
 6700.0,
 4400.0,
 7500.0,
 7600.0,
 6800.0,
 5700.0,
 7500.0,
 8000.0,
 7500.0,
 8000.0,
 6000.0,
 9100.0,
 11800.0,
 7800.0,
 6900.0,
 4400.0,
 6000.0,
 15100.0,
 7600.0,
 5800.0,
 6300.0,
 7700.0,
 7000.0,
 1300.0,
 8100.0,
 11200.0,
 5100.0,
 22800.0,
 9500.0,
 8100.0,
 7700.0,
 6400.0,
 5500.0,
 6000.0,
 6700.0,
 5200.0,
 6600.0,
 6600.0,
 15500.0,
 5600.0,
 4900.0,
 6200.0,
 5400.0,
 12900.0,
 20700.0,
 6400.0,
 4800.0,
 8900.0,
 15600.0,
 23100.0,
 4900.0,
 4600.0,
 6300.0,
 788.0,
 10100.0,
 11600.0,
 8900.0,
 6300.0,
 5600.0,
 8100.0,
 8100.0,
 6600.0,
 8900.0,
 15700.0,
 5700.0,
 14900.0,
 8500.0,
 3600.0,
 7600.0,
 7200.0,
 5800.0,
 6900.0,
 11000.0,
 6600.0,
 6700.0,
 10300.0,
 1400.0,
 8300.0,
 6000.0,
 6700.0,
 21600.0,
 4200.0,
 12700.0,
 10300.0,
 4400.0,
 11400.0,
 6200.0]

In [1297]:
tint

[10700.0,
 8400.0,
 5800.0,
 5700.0,
 4900.0,
 2300.0,
 7700.0,
 2500.0,
 4000.0,
 3900.0,
 3200.0,
 1800.0,
 1700.0,
 1500.0,
 5100.0,
 2000.0,
 675.0,
 1600.0,
 2400.0,
 3000.0,
 841.0,
 1500.0,
 2900.0,
 1100.0,
 1300.0,
 2100.0,
 567.0,
 892.0,
 1100.0,
 1000.0,
 544.0,
 641.0,
 1400.0,
 1200.0,
 683.0,
 808.0,
 974.0,
 700.0,
 543.0,
 1400.0,
 635.0,
 486.0,
 820.0,
 571.0,
 452.0,
 490.0,
 765.0,
 882.0,
 663.0,
 433.0,
 611.0,
 607.0,
 559.0,
 651.0,
 356.0,
 419.0,
 760.0,
 499.0,
 524.0,
 247.0,
 411.0,
 321.0,
 590.0,
 778.0,
 404.0,
 762.0,
 484.0,
 398.0,
 255.0,
 635.0,
 357.0,
 727.0,
 771.0,
 327.0,
 445.0,
 612.0,
 414.0,
 571.0,
 812.0,
 494.0,
 464.0,
 320.0,
 242.0,
 319.0,
 461.0,
 871.0,
 156.0,
 262.0,
 457.0,
 271.0,
 542.0,
 338.0,
 460.0,
 344.0,
 376.0,
 548.0,
 597.0,
 545.0,
 658.0,
 494.0,
 434.0,
 247.0,
 344.0,
 275.0,
 309.0,
 413.0,
 501.0,
 200.0,
 600.0,
 366.0,
 250.0,
 289.0,
 369.0,
 299.0,
 348.0,
 524.0,
 575.0,
 349.0,
 159.0,
 335.0,
 303.0,
 200.0,
 168.0,
 116.0,
 157.0,
 354.0,
 384.0,
 327.0,
 474.0,
 444.0,
 241.0,
 770.0,
 218.0,
 615.0,
 255.0,
 520.0,
 336.0,
 281.0,
 633.0,
 246.0,
 235.0,
 204.0,
 286.0,
 241.0,
 376.0,
 393.0,
 416.0,
 211.0,
 327.0,
 189.0,
 320.0,
 213.0,
 268.0,
 246.0,
 341.0,
 272.0,
 221.0,
 771.0,
 277.0,
 372.0,
 160.0,
 92.0,
 219.0,
 351.0,
 213.0,
 289.0,
 259.0,
 216.0,
 215.0,
 162.0,
 238.0,
 235.0,
 207.0,
 261.0,
 210.0,
 317.0,
 155.0,
 182.0,
 229.0,
 627.0,
 190.0,
 239.0,
 225.0,
 172.0,
 141.0,
 272.0,
 368.0,
 183.0,
 221.0,
 325.0,
 173.0,
 209.0,
 245.0,
 208.0,
 368.0,
 242.0,
 153.0,
 166.0,
 325.0,
 221.0,
 212.0,
 180.0,
 187.0,
 86.0,
 178.0,
 211.0,
 80.0,
 286.0,
 369.0,
 236.0,
 246.0,
 207.0,
 277.0,
 88.0,
 132.0,
 265.0,
 151.0,
 125.0,
 233.0,
 142.0,
 155.0,
 163.0,
 176.0,
 341.0,
 157.0,
 289.0,
 163.0,
 226.0,
 190.0,
 275.0,
 157.0,
 292.0,
 314.0,
 56.0,
 140.0,
 267.0,
 275.0,
 156.0,
 222.0,
 140.0,
 141.0,
 243.0,
 199.0,
 169.0,
 209.0,
 204.0,
 151.0,
 325.0,
 216.0,
 262.0,
 84.0,
 247.0,
 235.0,
 196.0,
 144.0,
 138.0,
 145.0,
 267.0,
 160.0,
 203.0,
 285.0,
 159.0,
 182.0,
 186.0,
 229.0,
 182.0,
 198.0,
 256.0,
 131.0,
 137.0,
 203.0,
 390.0,
 215.0,
 115.0,
 98.0,
 257.0,
 279.0,
 148.0,
 115.0,
 105.0,
 312.0,
 168.0,
 149.0,
 190.0,
 126.0,
 269.0,
 137.0,
 255.0,
 176.0,
 313.0,
 134.0,
 240.0,
 235.0,
 211.0,
 89.0,
 132.0,
 317.0,
 152.0,
 164.0,
 112.0,
 105.0,
 104.0,
 184.0,
 189.0,
 155.0,
 82.0,
 139.0,
 164.0,
 90.0,
 307.0,
 169.0,
 128.0,
 173.0,
 132.0,
 228.0,
 167.0,
 176.0,
 103.0,
 187.0,
 79.0,
 73.0,
 136.0,
 133.0,
 370.0,
 126.0,
 203.0,
 143.0,
 220.0,
 457.0,
 112.0,
 202.0,
 199.0,
 134.0,
 148.0,
 111.0,
 184.0,
 197.0,
 169.0,
 139.0,
 241.0,
 264.0,
 116.0,
 123.0,
 133.0,
 116.0,
 157.0,
 124.0,
 152.0,
 165.0,
 152.0,
 72.0,
 328.0,
 88.0,
 179.0,
 298.0,
 69.0,
 67.0,
 200.0,
 148.0,
 334.0,
 212.0,
 95.0,
 227.0,
 121.0,
 105.0,
 187.0,
 194.0,
 143.0,
 220.0,
 167.0,
 108.0,
 163.0,
 114.0,
 72.0,
 122.0,
 163.0,
 138.0,
 76.0,
 158.0,
 104.0,
 201.0,
 79.0,
 189.0,
 113.0,
 104.0,
 113.0,
 166.0,
 164.0,
 235.0,
 221.0,
 396.0,
 75.0,
 121.0,
 97.0,
 89.0,
 140.0,
 106.0,
 235.0,
 93.0,
 116.0,
 129.0,
 112.0,
 185.0,
 187.0,
 377.0,
 97.0,
 74.0,
 96.0,
 118.0,
 139.0,
 201.0,
 134.0,
 124.0,
 104.0,
 91.0,
 124.0,
 110.0,
 92.0,
 74.0,
 110.0,
 133.0,
 136.0,
 153.0,
 113.0,
 67.0,
 108.0,
 124.0,
 115.0,
 106.0,
 74.0,
 192.0,
 342.0,
 129.0,
 96.0,
 119.0,
 101.0,
 565.0,
 157.0,
 139.0,
 64.0,
 564.0,
 125.0,
 253.0,
 95.0,
 111.0,
 88.0,
 151.0,
 73.0,
 54.0,
 101.0,
 152.0,
 286.0,
 211.0,
 91.0,
 105.0,
 86.0,
 279.0,
 859.0,
 128.0,
 67.0,
 202.0,
 152.0,
 553.0,
 70.0,
 84.0,
 99.0,
 14.0,
 175.0,
 192.0,
 117.0,
 121.0,
 101.0,
 97.0,
 106.0,
 98.0,
 146.0,
 185.0,
 71.0,
 183.0,
 129.0,
 93.0,
 66.0,
 178.0,
 75.0,
 82.0,
 135.0,
 110.0,
 144.0,
 115.0,
 60.0,
 175.0,
 99.0,
 155.0,
 297.0,
 74.0,
 150.0,
 160.0,
 130.0,
 104.0,
 99.0]

In [1293]:
job

[450000.0, 5800.0, 4100.0]

In [ ]:
df['Salaries'] = df['Salaries'].replace('k','',regex = True).as

In [94]:
for j in df['Reviews']
if 'k' in df['Reviews'][0]:
    print(True)

True

In [2382]:
# for j in df['Reviews']:
#     print(j)